CREATE TABLE VOTE_DETAIL
(
    ID          BIGSERIAL PRIMARY KEY,
    VOTE_ID     BIGINT      NOT NULL,
    VOTE_FOR    TEXT        NOT NULL,
    RATING      INT         NOT NULL,
    EXTRA       TEXT,
    CREATE_TIME TIMESTAMPTZ NOT NULL DEFAULT NOW()
);